// Données mockées pour ECOPYE Pro Chantier
// Toutes les données sont fictives - aucune donnée réelle

export const MOCK_COMPANY = {
  id: 'company-1',
  name: 'Durand Rénovation Services',
  ownerName: 'Jean Durand',
  siret: '82394710200013',
  trade: 'RENOVATION_SALLE_DE_BAIN',
  address: '45 Rue des Artisans',
  city: 'Lyon',
  postalCode: '69003',
  phone: '04 78 12 34 56',
  email: 'contact@durand-renovation.fr',
  vatNumber: 'FR28823947102',
  insuranceNumber: 'DEC-2024-00892',
  insuranceExpiryDate: new Date('2025-12-31'),
  logoUrl: null,
  monthlyRevenueTarget: 25000,
  active: true,
  onboardingCompleted: true,
}

export const MOCK_CLIENTS = [
  {
    id: 'client-1',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Marie',
    lastName: 'Laurent',
    email: 'marie.laurent@email.fr',
    phone: '06 12 34 56 78',
    address: '12 Rue de la Paix',
    city: 'Lyon',
    postalCode: '69001',
    notes: 'Cliente fidèle depuis 2 ans',
    trustScore: 9,
    active: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'client-2',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Thomas',
    lastName: 'Bernard',
    email: 'thomas.bernard@gmail.com',
    phone: '06 23 45 67 89',
    address: '8 Avenue Garibaldi',
    city: 'Villeurbanne',
    postalCode: '69100',
    notes: null,
    trustScore: 7,
    active: true,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: 'client-3',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Sophie',
    lastName: 'Moreau',
    email: 'sophie.moreau@outlook.fr',
    phone: '06 34 56 78 90',
    address: '23 Cours Julien',
    city: 'Marseille',
    postalCode: '13006',
    notes: 'Prudence sur les délais de paiement',
    trustScore: 5,
    active: true,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'client-4',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Ahmed',
    lastName: 'Rahmani',
    email: 'ahmed.rahmani@hotmail.fr',
    phone: '06 45 67 89 01',
    address: '5 Place de la Comédie',
    city: 'Montpellier',
    postalCode: '34000',
    notes: null,
    trustScore: 8,
    active: true,
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'client-5',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Claire',
    lastName: 'Dubois',
    email: 'claire.dubois@email.fr',
    phone: '06 56 78 90 12',
    address: '34 Rue de Rivoli',
    city: 'Paris',
    postalCode: '75004',
    notes: 'Client premium - appartement haussmannien',
    trustScore: 10,
    active: true,
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'client-6',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Julien',
    lastName: 'Garnier',
    email: 'julien.garnier@gmail.com',
    phone: '06 67 89 01 23',
    address: '17 Rue Nationale',
    city: 'Lille',
    postalCode: '59000',
    notes: null,
    trustScore: 6,
    active: true,
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-05-28'),
  },
  {
    id: 'client-7',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Nadia',
    lastName: 'Ferrand',
    email: 'nadia.ferrand@email.fr',
    phone: '06 78 90 12 34',
    address: '9 Rue du Taur',
    city: 'Toulouse',
    postalCode: '31000',
    notes: 'Rénovation complète maison',
    trustScore: 8,
    active: true,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'client-8',
    companyId: 'company-1',
    type: 'PARTICULIER' as const,
    firstName: 'Michel',
    lastName: 'Robert',
    email: 'michel.robert@orange.fr',
    phone: '06 89 01 23 45',
    address: '21 Cours Berriat',
    city: 'Grenoble',
    postalCode: '38000',
    notes: null,
    trustScore: 7,
    active: true,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-06-20'),
  },
]

export const MOCK_QUOTES = [
  {
    id: 'quote-1',
    companyId: 'company-1',
    clientId: 'client-1',
    number: 'DEV-2024-0001',
    title: 'Rénovation complète salle de bain 6m²',
    description: 'Rénovation totale incluant plomberie, carrelage, équipements sanitaires',
    status: 'ACCEPTE' as const,
    subtotalHT: 8500,
    vatAmount: 1700,
    totalTTC: 10200,
    depositPercentage: 30,
    laborCost: 3200,
    materialCost: 5300,
    expiresAt: new Date('2024-07-30'),
    acceptedAt: new Date('2024-06-10'),
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'quote-2',
    companyId: 'company-1',
    clientId: 'client-2',
    number: 'DEV-2024-0002',
    title: 'Remplacement chaudière et installation radiateurs',
    description: 'Dépose ancienne chaudière, pose chaudière gaz à condensation, 5 radiateurs',
    status: 'ENVOYE' as const,
    subtotalHT: 5800,
    vatAmount: 1160,
    totalTTC: 6960,
    depositPercentage: 30,
    laborCost: 2100,
    materialCost: 3700,
    expiresAt: new Date('2024-07-15'),
    createdAt: new Date('2024-06-08'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'quote-3',
    companyId: 'company-1',
    clientId: 'client-6',
    number: 'DEV-2024-0003',
    title: 'Mise aux normes électrique appartement',
    description: 'Remplacement tableau électrique, mise en conformité NF C 15-100',
    status: 'VU' as const,
    subtotalHT: 3200,
    vatAmount: 640,
    totalTTC: 3840,
    depositPercentage: 40,
    laborCost: 1800,
    materialCost: 1400,
    expiresAt: new Date('2024-07-20'),
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'quote-4',
    companyId: 'company-1',
    clientId: 'client-7',
    number: 'DEV-2024-0004',
    title: 'Pose carrelage salon et cuisine 45m²',
    description: 'Dépose ancien revêtement, pose carrelage format 60x60 rectifié',
    status: 'ACCEPTE' as const,
    subtotalHT: 4100,
    vatAmount: 820,
    totalTTC: 4920,
    depositPercentage: 30,
    laborCost: 2400,
    materialCost: 1700,
    expiresAt: new Date('2024-07-10'),
    acceptedAt: new Date('2024-06-15'),
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'quote-5',
    companyId: 'company-1',
    clientId: 'client-5',
    number: 'DEV-2024-0005',
    title: 'Peinture appartement 80m² - 4 pièces',
    description: 'Préparation murs, peinture 2 couches, plafonds inclus',
    status: 'BROUILLON' as const,
    subtotalHT: 2800,
    vatAmount: 560,
    totalTTC: 3360,
    depositPercentage: 30,
    laborCost: 2200,
    materialCost: 600,
    expiresAt: new Date('2024-08-01'),
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-20'),
  },
]

export const MOCK_PROJECTS = [
  {
    id: 'project-1',
    companyId: 'company-1',
    clientId: 'client-1',
    quoteId: 'quote-1',
    title: 'Rénovation salle de bain - Marie Laurent',
    description: 'Rénovation complète SDB 6m² - Lyon 1er',
    address: '12 Rue de la Paix',
    city: 'Lyon',
    postalCode: '69001',
    status: 'EN_COURS' as const,
    plannedBudget: 10200,
    actualBudget: 8900,
    startDate: new Date('2024-06-15'),
    endDate: new Date('2024-07-05'),
    progress: 65,
    riskLevel: 'FAIBLE' as const,
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-25'),
    steps: [
      { id: 's1', projectId: 'project-1', title: 'Devis signé', status: 'VALIDE_CLIENT', order: 1, validatedByClient: true },
      { id: 's2', projectId: 'project-1', title: 'Acompte reçu (30%)', status: 'TERMINE', order: 2, validatedByClient: false },
      { id: 's3', projectId: 'project-1', title: 'Préparation chantier', status: 'TERMINE', order: 3, validatedByClient: false },
      { id: 's4', projectId: 'project-1', title: 'Dépose ancienne installation', status: 'TERMINE', order: 4, validatedByClient: false },
      { id: 's5', projectId: 'project-1', title: 'Plomberie et étanchéité', status: 'EN_COURS', order: 5, validatedByClient: false },
      { id: 's6', projectId: 'project-1', title: 'Pose carrelage', status: 'EN_ATTENTE', order: 6, validatedByClient: false },
      { id: 's7', projectId: 'project-1', title: 'Installation équipements', status: 'EN_ATTENTE', order: 7, validatedByClient: false },
      { id: 's8', projectId: 'project-1', title: 'Finitions et nettoyage', status: 'EN_ATTENTE', order: 8, validatedByClient: false },
      { id: 's9', projectId: 'project-1', title: 'Réception client', status: 'EN_ATTENTE', order: 9, validatedByClient: false },
      { id: 's10', projectId: 'project-1', title: 'Paiement solde', status: 'EN_ATTENTE', order: 10, validatedByClient: false },
    ],
  },
  {
    id: 'project-2',
    companyId: 'company-1',
    clientId: 'client-4',
    quoteId: null,
    title: 'Remplacement chaudière - Ahmed Rahmani',
    description: 'Chaudière gaz condensation + 5 radiateurs',
    address: '5 Place de la Comédie',
    city: 'Montpellier',
    postalCode: '34000',
    status: 'PREPARATION' as const,
    plannedBudget: 6200,
    actualBudget: 0,
    startDate: new Date('2024-07-10'),
    endDate: new Date('2024-07-15'),
    progress: 10,
    riskLevel: 'FAIBLE' as const,
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-20'),
    steps: [],
  },
  {
    id: 'project-3',
    companyId: 'company-1',
    clientId: 'client-3',
    quoteId: null,
    title: 'Mise aux normes électrique - Sophie Moreau',
    description: 'Tableau électrique + conformité NF C 15-100',
    address: '23 Cours Julien',
    city: 'Marseille',
    postalCode: '13006',
    status: 'LITIGE_POTENTIEL' as const,
    plannedBudget: 3840,
    actualBudget: 4200,
    startDate: new Date('2024-05-20'),
    endDate: new Date('2024-06-10'),
    progress: 85,
    riskLevel: 'ELEVE' as const,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-06-20'),
    steps: [],
  },
  {
    id: 'project-4',
    companyId: 'company-1',
    clientId: 'client-7',
    quoteId: 'quote-4',
    title: 'Pose carrelage - Nadia Ferrand',
    description: 'Carrelage salon + cuisine 45m²',
    address: '9 Rue du Taur',
    city: 'Toulouse',
    postalCode: '31000',
    status: 'EN_ATTENTE_ACOMPTE' as const,
    plannedBudget: 4920,
    actualBudget: 0,
    startDate: new Date('2024-07-20'),
    endDate: new Date('2024-07-28'),
    progress: 5,
    riskLevel: 'FAIBLE' as const,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-15'),
    steps: [],
  },
]

export const MOCK_INVOICES = [
  {
    id: 'invoice-1',
    companyId: 'company-1',
    clientId: 'client-1',
    quoteId: 'quote-1',
    projectId: 'project-1',
    number: 'FAC-2024-0001',
    type: 'ACOMPTE' as const,
    status: 'PAYEE' as const,
    subtotalHT: 2550,
    vatAmount: 510,
    totalTTC: 3060,
    amountPaid: 3060,
    dueDate: new Date('2024-06-20'),
    issuedAt: new Date('2024-06-10'),
    paidAt: new Date('2024-06-18'),
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'invoice-2',
    companyId: 'company-1',
    clientId: 'client-1',
    quoteId: 'quote-1',
    projectId: 'project-1',
    number: 'FAC-2024-0002',
    type: 'FINALE' as const,
    status: 'EN_ATTENTE' as const,
    subtotalHT: 5950,
    vatAmount: 1190,
    totalTTC: 7140,
    amountPaid: 0,
    dueDate: new Date('2024-07-15'),
    issuedAt: new Date('2024-06-25'),
    paidAt: null,
    createdAt: new Date('2024-06-25'),
    updatedAt: new Date('2024-06-25'),
  },
  {
    id: 'invoice-3',
    companyId: 'company-1',
    clientId: 'client-3',
    quoteId: null,
    projectId: 'project-3',
    number: 'FAC-2024-0003',
    type: 'FINALE' as const,
    status: 'EN_RETARD' as const,
    subtotalHT: 3200,
    vatAmount: 640,
    totalTTC: 3840,
    amountPaid: 1500,
    dueDate: new Date('2024-06-05'),
    issuedAt: new Date('2024-06-01'),
    paidAt: null,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-20'),
  },
]

export const MOCK_PAYMENTS = [
  {
    id: 'payment-1',
    companyId: 'company-1',
    clientId: 'client-1',
    invoiceId: 'invoice-1',
    amount: 3060,
    status: 'REUSSI' as const,
    method: 'VIREMENT' as const,
    receiptNumber: 'REC-240618-001',
    simulatedAt: new Date('2024-06-18'),
    createdAt: new Date('2024-06-18'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'payment-2',
    companyId: 'company-1',
    clientId: 'client-3',
    invoiceId: 'invoice-3',
    amount: 1500,
    status: 'REUSSI' as const,
    method: 'CHEQUE' as const,
    receiptNumber: 'REC-240610-002',
    simulatedAt: new Date('2024-06-10'),
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-10'),
  },
]

export const MOCK_DASHBOARD_STATS = {
  revenueThisMonth: 18750,
  revenuePreviousMonth: 14200,
  quotesCount: 5,
  quotesAccepted: 2,
  invoicesOverdue: 1,
  activeProjects: 3,
  pendingPayments: 7140,
  estimatedMargin: 28,
  disputeAlerts: 1,
}

export const MOCK_REVENUE_DATA = [
  { mois: 'Jan', CA: 12000, objectif: 25000 },
  { mois: 'Fév', CA: 15500, objectif: 25000 },
  { mois: 'Mar', CA: 18200, objectif: 25000 },
  { mois: 'Avr', CA: 16800, objectif: 25000 },
  { mois: 'Mai', CA: 14200, objectif: 25000 },
  { mois: 'Juin', CA: 18750, objectif: 25000 },
]

export const MOCK_QUOTE_RATE_DATA = [
  { mois: 'Jan', envoyes: 8, acceptes: 5 },
  { mois: 'Fév', envoyes: 10, acceptes: 7 },
  { mois: 'Mar', envoyes: 12, acceptes: 8 },
  { mois: 'Avr', envoyes: 9, acceptes: 6 },
  { mois: 'Mai', envoyes: 11, acceptes: 8 },
  { mois: 'Juin', envoyes: 5, acceptes: 2 },
]

export const MOCK_TECHNICIANS = [
  {
    id: 'tech-1',
    companyId: 'company-1',
    name: 'Karim Benali',
    email: 'karim.benali@durand-renovation.fr',
    phone: '06 11 22 33 44',
    trade: 'PLOMBIER' as const,
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'tech-2',
    companyId: 'company-1',
    name: 'Lucas Petit',
    email: 'lucas.petit@durand-renovation.fr',
    phone: '06 55 66 77 88',
    trade: 'CARRELEUR' as const,
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

export const MOCK_USERS = [
  {
    id: 'user-1',
    name: 'Jean Durand',
    email: 'jean.durand@durand-renovation.fr',
    role: 'OWNER' as const,
    companyId: 'company-1',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    name: 'Sarah Martin',
    email: 'sarah.martin@durand-renovation.fr',
    role: 'ADMIN_COMPANY' as const,
    companyId: 'company-1',
    active: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]
